--------------------------------------------------------
-- Archivo creado  - lunes-enero-15-2018   
--------------------------------------------------------
REM INSERTING into SIGEBI_OAF.SIGB_ACCESORIO
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_ACTA
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_ACTA_DETALLE
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_AUTORIZACION
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_AUTORIZACION_ROL
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_AUTORIZACION_ROL_PERSONA
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_BIEN
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_BIEN_CARACTERISTICA
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_BIEN_SOLICITUD
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_CLASIFICACION
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_CONVENIO
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_DOCUMENTO
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_DOCUMENTO_AUTORIZACION
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_DONACION
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_DONACION_DETALLE
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_ESTADO
SET DEFINE OFF;
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('2','PENDIENTE','BIEN','2');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('4','PENDIENTE POR ACTIVACIÓN','BIEN','4');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('5','ACTIVO','BIEN','5');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('6','PENDIENTE POR INACTIVACIÓN','BIEN','6');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('7','INACTIVO','BIEN','7');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('1','PRE INGRESO','BIEN','1');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('13','INACTIVO','GENERAL','2');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('18','CREADA','NOTIFICACION','1');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('19','ENVIADA','NOTIFICACION','2');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('20','ENVIO FALLIDO','NOTIFICACION','3');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('8','NUEVO','INFORME_TECNICO','1');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('9','EN PROCESO','INFORME_TECNICO','2');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('10','APROBADO','INFORME_TECNICO','3');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('11','RECHAZADO','INFORME_TECNICO','4');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('12','ACTIVO','GENERAL','1');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('21','CREADA','EXCLUSION','1');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('22','EN TRAMITE','EXCLUSION','2');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('23','CERRADA','EXCLUSION','3');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('25','APROBADO','GENERAL','3');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('26','RECHAZADO','GENERAL','4');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('27','PENDIENTE','GENERAL','5');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('3','PENDIENTE POR SINCRONIZACIÓN','BIEN','3');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('14','PENDIENTE','ACTA','1');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('15','PROCESO','ACTA','2');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('16','APLICADA','ACTA','3');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('17','RECHAZADA','ACTA','4');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('24','ANULADO','INFORME_TECNICO','5');
Insert into SIGEBI_OAF.SIGB_ESTADO (ID_ESTADO,NOMBRE,DOMINIO,ESTADO) values ('28','ANULADO','GENERAL','6');
REM INSERTING into SIGEBI_OAF.SIGB_EXCLUSION
SET DEFINE OFF;
Insert into SIGEBI_OAF.SIGB_EXCLUSION (ID_SOLICITUD,ID_TIPO) values ('1','28');
Insert into SIGEBI_OAF.SIGB_EXCLUSION (ID_SOLICITUD,ID_TIPO) values ('2','29');
Insert into SIGEBI_OAF.SIGB_EXCLUSION (ID_SOLICITUD,ID_TIPO) values ('4','31');
Insert into SIGEBI_OAF.SIGB_EXCLUSION (ID_SOLICITUD,ID_TIPO) values ('5','28');
Insert into SIGEBI_OAF.SIGB_EXCLUSION (ID_SOLICITUD,ID_TIPO) values ('6','28');
REM INSERTING into SIGEBI_OAF.SIGB_EXCLUSION_DETALLE
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_IDENTIFICACION
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_INFORME_TECNICO
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_NOTIFICACION
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_PRESTAMO
SET DEFINE OFF;
REM INSERTING into SIGEBI_OAF.SIGB_PRESTAMO_DETALLE
SET DEFINE OFF;
