--------------------------------------------------------
-- Archivo creado  - lunes-enero-15-2018   
--------------------------------------------------------
REM INSERTING into SIGEBI_OAF.SIGB_TIPO
SET DEFINE OFF;
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('2','INMUEBLE','TIPO','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('1','MUEBLE','TIPO','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('17','REUBICAR','INFORME_TECNICO','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('18','USAR PIEZAS','INFORME_TECNICO','5');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('19','DESECHAR','INFORME_TECNICO','4');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('20','REPARAR','INFORME_TECNICO','6');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('21','DONAR','INFORME_TECNICO','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('22','OTROS','INFORME_TECNICO','3');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('29','DESECHO','EXCLUSION','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('30','PRESTAMO','EXCLUSION','3');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('31','RETORNO','EXCLUSION','4');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('23','Donación','PROCESO','3');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('24','Exclusión por desecho','PROCESO','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('25','Exclusión por donación','PROCESO','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('28','DONACION','EXCLUSION','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('10','PLACA','IDENTIFICACION','8');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('11','ID UNIDAD','IDENTIFICACION','7');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('26','DONACIÓN','ACTA','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('27','DESECHO','ACTA','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('34','TRASLADO','PROCESO','4');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('3','MARCA','CARACTERISTICA','3');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('4','MODELO','CARACTERISTICA','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('5','SERIE','CARACTERISTICA','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('6','COMPRA DIRECTA','ORIGEN','9');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('7','DONACIÓN DE FUND. UCR','ORIGEN','8');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('8','DONACIÓN EXTERNA','ORIGEN','7');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('9','GARANTÍA','ORIGEN','6');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('12','NACIMIENTO','ORIGEN','5');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('13','REPOSICIÓN','ORIGEN','4');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('14','COMPRA FONDOS TRABAJO','ORIGEN','3');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('15','CONFECCIONES','ORIGEN','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('16','PERMUTAS','ORIGEN','2');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('32','DOCUMENTO','DOCUMENTO','1');
Insert into SIGEBI_OAF.SIGB_TIPO (ID_TIPO,NOMBRE,DOMINIO,VALOR) values ('33','ADJUNTO','ADJUNTO','1');
