--------------------------------------------------------
-- Archivo creado  - lunes-enero-15-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SIGB_TRASLADO
--------------------------------------------------------

  CREATE TABLE "SIGEBI_OAF"."SIGB_TRASLADO" 
   (	"ID_TRASLADO" NUMBER, 
	"ID_PERSONA" NUMBER, 
	"ID_UNIDAD_RECIBE" NUMBER, 
	"ID_PERSONA_RECIBE" NUMBER, 
	"ID_UBICACION" NUMBER, 
	"OBSERVACIONES" VARCHAR2(500 BYTE), 
	"ID_SOLICITUD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SIGEBI_OAF"."SIGB_TRASLADO"."ID_TRASLADO" IS 'Identificación del traslado';
   COMMENT ON COLUMN "SIGEBI_OAF"."SIGB_TRASLADO"."ID_PERSONA" IS 'Persona que genera el traslado';
   COMMENT ON COLUMN "SIGEBI_OAF"."SIGB_TRASLADO"."ID_UNIDAD_RECIBE" IS 'Unidad que recibirá el traslado';
   COMMENT ON COLUMN "SIGEBI_OAF"."SIGB_TRASLADO"."ID_PERSONA_RECIBE" IS 'Persona que recibe el traslado';
   COMMENT ON COLUMN "SIGEBI_OAF"."SIGB_TRASLADO"."ID_UBICACION" IS 'Lugar al que se enviarán los bienes (ubicacion)';
   COMMENT ON COLUMN "SIGEBI_OAF"."SIGB_TRASLADO"."OBSERVACIONES" IS 'Observaciones del traslado';
REM INSERTING into SIGEBI_OAF.SIGB_TRASLADO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_SIGB_TRASLADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "SIGEBI_OAF"."PK_SIGB_TRASLADO" ON "SIGEBI_OAF"."SIGB_TRASLADO" ("ID_TRASLADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SIGB_TRASLADO
--------------------------------------------------------

  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" MODIFY ("ID_SOLICITUD" NOT NULL ENABLE);
  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" ADD CONSTRAINT "SIGB_TRASLADO_PK" PRIMARY KEY ("ID_TRASLADO")
  USING INDEX (CREATE UNIQUE INDEX "SIGEBI_OAF"."PK_SIGB_TRASLADO" ON "SIGEBI_OAF"."SIGB_TRASLADO" ("ID_TRASLADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" )  ENABLE;
  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" MODIFY ("ID_UBICACION" NOT NULL ENABLE);
  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" MODIFY ("ID_PERSONA_RECIBE" NOT NULL ENABLE);
  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" MODIFY ("ID_UNIDAD_RECIBE" NOT NULL ENABLE);
  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "SIGEBI_OAF"."SIGB_TRASLADO" MODIFY ("ID_TRASLADO" NOT NULL ENABLE);
